export const queryKeys = {
  me: ["me"] as const,
  userConfigs: ["user-configs"] as const,
  videoModelCatalog: ["video-model-catalog"] as const,
  projects: ["projects"] as const,
  projectModels: (projectId: string) => ["project-models", projectId] as const,
  promptPresets: (kind: string) => ["prompt-presets", kind] as const,
  episodes: (projectId: string) => ["episodes", projectId] as const,
  episode: (projectId: string, episodeId: string) => ["episode", projectId, episodeId] as const,
  characters: (projectId: string) => ["characters", projectId] as const,
  props: (projectId: string) => ["props", projectId] as const,
  voices: (projectId: string) => ["voices", projectId] as const,
  assets: (projectId: string) => ["assets", projectId] as const,
  exports: (projectId: string) => ["exports", projectId] as const,
  adminUsers: ["admin-users"] as const,
  adminUsageLogs: (search: string, page: number) => ["admin-usage-logs", search, page] as const,
  adminErrorLogs: (search: string, page: number) => ["admin-error-logs", search, page] as const,
  invitationCodes: (status: string, search: string, page: number) => ["invitation-codes", status, search, page] as const,
  redemptionCodes: (status: string, page: number) => ["redemption-codes", status, page] as const,
  officialConfigs: ["official-configs"] as const,
  usageLogs: ["usage-logs"] as const,
  userVoices: ["user-voices"] as const,
  chatSessions: ["chat-sessions"] as const,
  chatMessages: (sessionId: string | null) => ["chat-messages", sessionId] as const,
};
