"""add user nickname and remove config verification

Revision ID: 2df5b20c732e
Revises: 345000649eb5
Create Date: 2026-08-13 14:19:27.707219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2df5b20c732e'
down_revision: Union[str, Sequence[str], None] = '345000649eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    model_config_columns = {column['name'] for column in inspect(op.get_bind()).get_columns('model_configs')}
    if 'is_verified' in model_config_columns:
        op.execute("UPDATE model_configs SET is_enabled = 0, is_active = 0 WHERE NOT COALESCE(is_verified, 0)")
        with op.batch_alter_table('model_configs', schema=None) as batch_op:
            batch_op.drop_column('is_verified')

    user_columns = {column['name'] for column in inspect(op.get_bind()).get_columns('users')}
    if 'nickname' not in user_columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=True))

    # ### end Alembic commands ###
